batch_size: 16 # batch size Per GPU
num_workers: 6
print_freq: 10
save_freq: 100
val_freq: 10

# data augmentation
data:
  datasets: 'shapenetpart'
  data_root: './data'
  input_features_dim: 3
  num_parts:
    - 4
    - 2
    - 2
    - 4
    - 4
    - 3
    - 3
    - 2
    - 4
    - 2
    - 6
    - 2
    - 3
    - 3
    - 3
    - 3
  num_classes: 16
  num_points: 2048
  in_radius: 2.0
  x_angle_range: 0.0
  y_angle_range: 0.0
  z_angle_range: 3.1415926
  scale_low: 0.7
  scale_high: 1.3
  noise_std: 0.001
  noise_clip: 0.05
  translate_range: 0.0
  sampleDl: 0.02

# ---------------------------------------------------------------------------- #
# Training options
# ---------------------------------------------------------------------------- #
epochs: 600
start_epoch: 1
warmup_epoch:  -1

lr_scheduler:
  name: 'cosine'  # step,cosine
  decay_steps: 1
  decay_rate: 0.9885531
  on_epoch: True

optimizer:
  name: 'adamW'
  weight_decay: 0.00001
  momentum: 0.9
  lr: 0.00125  # LR per batch! for batch size 8 per GPU and 2 gpus -> lr *= 8*2

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: './log/shapenetpart'

wandb:
  project: ASSA-Net-ShapeNetPart
